version: "3.8"

services:
  postgres:
    image: postgres:14
    command: postgres -c log_statement=all
    environment:
      - POSTGRES_DB=${DATABASE_NAME}
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"

  app:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    volumes:
      - .:/home/logistic
    ports:
      - "8000:8000"
    depends_on:
      - postgres

volumes:
  postgres_data:

