# Generated by Django 3.0.3 on 2020-05-09 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InventorySummary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_count', models.IntegerField()),
            ],
            options={
                'db_table': 'inventory_summary',
                'ordering': ['sku'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='LastReadingsSnapshot',
            fields=[
                ('epc', models.CharField(max_length=150, primary_key=True, serialize=False)),
                ('timestamp_reading', models.DateTimeField()),
            ],
            options={
                'db_table': 'last_readings_snapshot',
                'managed': False,
            },
        ),
    ]
