# Generated by Django 3.0.3 on 2020-02-19 16:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=140)),
                ('description', models.CharField(blank=True, max_length=140, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Node',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=140)),
                ('description', models.CharField(blank=True, max_length=140, null=True)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='rfid.Location')),
            ],
        ),
        migrations.CreateModel(
            name='Reader',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=140)),
                ('serial_number', models.CharField(max_length=140, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ReaderAntenna',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=140)),
                ('serial_number', models.CharField(max_length=140, unique=True)),
                ('reader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rfid.Reader')),
            ],
        ),
        migrations.CreateModel(
            name='ReaderBrand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=140)),
            ],
        ),
        migrations.CreateModel(
            name='Reading',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('epc', models.CharField(max_length=24)),
                ('antenna', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='rfid.ReaderAntenna')),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='rfid.Node')),
                ('reader', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='rfid.Reader')),
            ],
        ),
        migrations.AddField(
            model_name='reader',
            name='brand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='rfid.ReaderBrand'),
        ),
    ]
