# Generated by Django 4.0 on 2022-12-06 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rfid', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sku',
            name='reference_image',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
