# Generated by Django 3.0.3 on 2020-02-24 16:17

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rfid', '0002_reading_timestamp_reading'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('epc', models.CharField(max_length=48, primary_key=True, serialize=False)),
                ('last_seen_timestamp', models.DateTimeField(null=True)),
                ('data', django.contrib.postgres.fields.jsonb.JSONField()),
                ('last_seen_location', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='rfid.Location')),
            ],
        ),
    ]
