# Generated by Django 3.0.3 on 2020-05-09 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rfid', '0002_auto_20200508_2236'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sites',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
    ]
