# Generated by Django 4.0 on 2023-01-23 23:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rfid', '0002_sku_reference_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inventorysummary',
            options={'managed': False, 'ordering': ['sku']},
        ),
    ]
