# Generated by Django 3.0.3 on 2020-02-24 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rfid', '0003_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='display_name',
            field=models.CharField(default='Test', max_length=200),
            preserve_default=False,
        ),
    ]
