# Generated by Django 3.0.3 on 2020-05-10 23:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rfid', '0003_sites'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='origin_site',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='rfid.Sites'),
        ),
        migrations.AlterField(
            model_name='sku',
            name='reference_image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
