# Generated by Django 3.0.3 on 2020-02-24 19:39

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rfid', '0004_item_display_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='data',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
    ]
