# Generated by Django 3.0.3 on 2020-02-28 03:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rfid', '0005_auto_20200224_1939'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransferOrderItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(choices=[('RE', 'Solicitado'), ('AL', 'Alistado'), ('NOE', 'No entregado'), ('EN', 'Entregado')], default='RE', max_length=3)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rfid.Item')),
            ],
        ),
        migrations.CreateModel(
            name='TransferOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expected_completion_date', models.DateField(null=True)),
                ('actual_completion_date', models.DateTimeField(null=True)),
                ('state', models.CharField(choices=[('RE', 'Solicitado'), ('IN', 'Incompleto'), ('CO', 'Completado')], default='RE', max_length=3)),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='rfid.Location')),
            ],
        ),
    ]
