# Generated by Django 3.0.3 on 2020-02-28 04:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rfid', '0006_transferorder_transferorderitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='transferorderitem',
            name='order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='rfid.TransferOrder'),
        ),
        migrations.AlterField(
            model_name='transferorder',
            name='actual_completion_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='transferorder',
            name='expected_completion_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='transferorderitem',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='rfid.Item'),
        ),
    ]
