# Generated by Django 3.0.3 on 2020-02-28 04:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rfid', '0007_auto_20200228_0401'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='transferorderitem',
            unique_together={('order', 'item')},
        ),
    ]
