# Generated by Django 3.0.3 on 2020-03-13 16:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rfid', '0008_auto_20200228_0403'),
    ]

    operations = [
        migrations.CreateModel(
            name='SKU',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='item',
            name='in_transit',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='item',
            name='sku',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='rfid.SKU'),
        ),
    ]
