# Generated by Django 3.0.3 on 2020-03-16 04:30

import django.contrib.postgres.fields.hstore
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rfid', '0010_auto_20200316_0411'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='data',
        ),
        migrations.RemoveField(
            model_name='sku',
            name='codigo_SAP',
        ),
        migrations.RemoveField(
            model_name='sku',
            name='descripcion',
        ),
        migrations.RemoveField(
            model_name='sku',
            name='modelo',
        ),
        migrations.RemoveField(
            model_name='sku',
            name='ni_name',
        ),
        migrations.RemoveField(
            model_name='sku',
            name='plataforma_fuente_unidad',
        ),
        migrations.RemoveField(
            model_name='sku',
            name='tipo_unidad',
        ),
        migrations.AddField(
            model_name='sku',
            name='data',
            field=django.contrib.postgres.fields.hstore.HStoreField(blank=True, null=True),
        ),
    ]
