# Generated by Django 3.0.3 on 2020-03-16 04:31

import django.contrib.postgres.fields.hstore
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rfid', '0011_auto_20200316_0430'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='data',
            field=django.contrib.postgres.fields.hstore.HStoreField(blank=True, null=True),
        ),
    ]
