# Generated by Django 3.0.3 on 2020-03-24 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rfid', '0014_reading_action'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventorySummary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField()),
            ],
            options={
                'db_table': 'inventory_summary',
                'managed': False,
            },
        ),
        migrations.AddField(
            model_name='item',
            name='last_seen_action',
            field=models.CharField(choices=[('IN', 'Entrada'), ('OUT', 'Salida'), ('READ', 'Lectura')], default='IN', max_length=10),
        ),
        migrations.AlterField(
            model_name='reading',
            name='action',
            field=models.CharField(choices=[('IN', 'Entrada'), ('OUT', 'Salida'), ('READ', 'Lectura')], default='READ', max_length=10),
        ),
    ]
