# Generated by Django 3.0.3 on 2020-03-26 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rfid', '0015_auto_20200324_1846'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='epc',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
