# Generated by Django 3.0.3 on 2020-03-30 02:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rfid', '0018_auto_20200327_1417'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransferOrderTrancking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp_reading', models.DateTimeField(auto_now_add=True)),
                ('latitude', models.DecimalField(decimal_places=7, max_digits=10)),
                ('longitude', models.DecimalField(decimal_places=7, max_digits=10)),
                ('order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='rfid.TransferOrder')),
            ],
        ),
    ]
