# Generated by Django 3.0.3 on 2020-03-30 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rfid', '0019_transferordertrancking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transferorder',
            name='state',
            field=models.CharField(choices=[('RE', 'Solicitado'), ('IP', 'En Alistamiento'), ('IT', 'En Tránsito'), ('CO', 'Entregado')], default='RE', max_length=3),
        ),

        migrations.RunSQL('create or replace view  last_readings_snapshot as'
                            'select' 
                            'reading.epc , reading.timestamp_reading, reading .antenna_id, reading .reader_id, reading.node_id,'
                            'item.sku_id ,'
                            'node.location_id' 
                            'from rfid_reading as reading'
                            'left join rfid_item as item on reading.epc = item.epc' 
                            'left join rfid_node as node on reading.node_id = node.id' 
                            'where (reading.epc,reading.timestamp_reading) in' 
                            '(select epc, max(timestamp_reading) from rfid_reading group by epc)'
                          )
    ]






