# Generated by Django 3.0.3 on 2020-03-30 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rfid', '0020_auto_20200330_0257'),
    ]

    operations = [
        migrations.CreateModel(
            name='LastReadingsSnapshot',
            fields=[
                ('epc', models.CharField(max_length=150, primary_key=True, serialize=False)),
                ('timestamp_reading', models.DateTimeField()),
            ],
            options={
                'db_table': 'last_readings_snapshot',
                'managed': False,
            },
        ),
        migrations.AlterField(
            model_name='transferorderitem',
            name='state',
            field=models.CharField(choices=[('RE', 'Por alistar'), ('AL', 'Alistado'), ('NOE', 'No entregado'), ('EN', 'Entregado')], default='RE', max_length=3),
        ),
    ]
