# Generated by Django 3.0.3 on 2020-03-30 18:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rfid', '0022_inventoryreport_inventoryreportline'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventoryreport',
            name='start_date',
        ),
        migrations.CreateModel(
            name='InventoryRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField(auto_now_add=True)),
                ('finish_date', models.DateTimeField(blank=True, null=True)),
                ('wait_minutes', models.PositiveIntegerField(default=10)),
                ('all_locations', models.BooleanField(default=False)),
                ('all_skus', models.BooleanField(default=False)),
                ('end_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='inv_request_end', to='rfid.Location')),
                ('end_sku', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='inv_request_end', to='rfid.SKU')),
                ('init_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='inv_request_init', to='rfid.Location')),
                ('init_sku', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='inv_request_init', to='rfid.SKU')),
            ],
        ),
        migrations.AddField(
            model_name='inventoryreport',
            name='inventory_request',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='rfid.InventoryRequest'),
        ),
    ]
