# Generated by Django 3.0.3 on 2020-03-30 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rfid', '0024_inventoryreport_created'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inventoryreportline',
            old_name='unidad',
            new_name='packing_unit',
        ),
    ]
