# Generated by Django 3.0.3 on 2020-04-03 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rfid', '0025_auto_20200330_1839'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TransferOrderTrancking',
            new_name='TransferOrderTrncking',
        ),
        migrations.AlterModelOptions(
            name='inventorysummary',
            options={'managed': False, 'ordering': ['sku']},
        ),
    ]
