# Generated by Django 3.0.3 on 2020-04-03 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rfid', '0026_auto_20200403_1600'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TransferOrderTrncking',
            new_name='TransferOrderTracking',
        ),
    ]
