# Generated by Django 3.0.3 on 2020-04-07 15:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rfid', '0027_auto_20200403_1601'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='current_location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='current_items', to='rfid.Location'),
        ),
    ]
