# Generated by Django 4.0 on 2023-02-20 01:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InventorySummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_count', models.IntegerField()),
            ],
            options={
                'db_table': 'inventory_summary',
                'ordering': ['sku'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=140)),
                ('description', models.CharField(blank=True, max_length=140, null=True)),
            ],
            options={
                'db_table': 'location',
            },
        ),
        migrations.CreateModel(
            name='PackingUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('description', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'packing_unit',
            },
        ),
        migrations.CreateModel(
            name='Sites',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'sites',
            },
        ),
        migrations.CreateModel(
            name='SKU',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(max_length=200)),
                ('reference_image', models.ImageField(null=True, upload_to='')),
                ('datasheet', models.FileField(blank=True, null=True, upload_to='')),
                ('data', models.JSONField(blank=True, null=True)),
            ],
            options={
                'db_table': 'sku',
            },
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.location')),
            ],
            options={
                'db_table': 'position',
            },
        ),
        migrations.AddField(
            model_name='location',
            name='site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.sites'),
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('epc', models.CharField(max_length=150, primary_key=True, serialize=False)),
                ('last_seen_timestamp', models.DateTimeField(null=True)),
                ('last_seen_action', models.CharField(choices=[('IN', 'Entrada'), ('OUT', 'Salida'), ('READ', 'Lectura')], default='IN', max_length=10)),
                ('display_name', models.CharField(max_length=200)),
                ('data', models.JSONField(blank=True, null=True)),
                ('in_transit', models.BooleanField(default=False)),
                ('image', models.ImageField(null=True, upload_to='')),
                ('current_location', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='current_items', to='inventory.location')),
                ('last_seen_location', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='inventory.location')),
                ('origin_site', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='inventory.sites')),
                ('packing_unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='inventory.packingunit')),
                ('sku', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='inventory.sku')),
            ],
            options={
                'db_table': 'item',
            },
        ),
        migrations.RunSQL(
            """
            create or replace view  inventory_summary as select 
                row_number() over() as id,
                sku_id, 
                last_seen_location_id,
                count(sku_id) as total_count
            from item
            group by sku_id, last_seen_location_id
            order by id;
            """
        ),
    ]
