# Generated by Django 4.0 on 2023-02-23 02:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_item_current_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='last_seen_position',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='last_items', to='inventory.position'),
        ),
    ]
